openapi: 3.0.0
info:
    title: Front end
    description: Front end
    version: 0.0.1
paths:
    /:
        post:
            operationId: inference.controller.run
            responses:
                "200":
                    description: "Check For fanity words"
                    content:
                        application/json:
                          schema:
                            type: object


    /listwords:
        get:
          operationId: inference.controller.listwords
              
        responses:
            "200":
                description: "List of fanity words"
                content:
                    application/json:
                      schema:
                        type: object

    /addword:
        post:
            operationId: inference.controller.addword
            requestBody:
                content:    
                    encoding:
                      file:
                        contentType: text/plain
            responses:
                "200":
                  description: "Add fanity word to the list"
                        content:
                        application/json:
                            schema:
                            type: object
    /removeword:
        post:
            operationId: inference.controller.removeword
            requestBody:
                content:    
                    encoding:
                      file:
                        contentType: text/plain
            responses:
                "200":
                  description: "Remove fanity word to the list"
                        content:
                        application/json:
                            schema:
                            type: object